// packages/crud/shell/react/src/lib/components/filter/filter.tsx
import { FieldType } from '@smartsoft001/models';

import { SmartCrudFilterCheck } from './check/filter-check';
import { SmartCrudFilterDate } from './date/filter-date';
import { SmartCrudFilterDateTime } from './date-time/filter-date-time';
import { SmartCrudFilterDateWithEdit } from './date-with-edit/filter-date-with-edit';
import { SmartCrudFilterProps } from './filter.types';
import { SmartCrudFilterFlag } from './flag/filter-flag';
import { SmartCrudFilterInt } from './int/filter-int';
import { SmartCrudFilterRadio } from './radio/filter-radio';
import { SmartCrudFilterText } from './text/filter-text';

function SmartCrudFilterField(props: SmartCrudFilterProps) {
  switch (props.item?.fieldType) {
    case FieldType.date:
      return <SmartCrudFilterDate {...props} />;
    case FieldType.dateWithEdit:
      return <SmartCrudFilterDateWithEdit {...props} />;
    case FieldType.dateTime:
      return <SmartCrudFilterDateTime {...props} />;
    case FieldType.radio:
      return <SmartCrudFilterRadio {...props} />;
    case FieldType.check:
      return <SmartCrudFilterCheck {...props} />;
    case FieldType.flag:
      return <SmartCrudFilterFlag {...props} />;
    case FieldType.int:
      return <SmartCrudFilterInt {...props} />;
    default:
      return <SmartCrudFilterText {...props} />;
  }
}

/**
 * `<smart-crud-filter>` (Angular `FilterComponent`): the filter field of the
 * item's field type (date, date with edit, date-time, radio, check, flag,
 * int; text otherwise), reading and writing the list filter through the
 * feature's facade.
 */
export function SmartCrudFilter(props: SmartCrudFilterProps) {
  return (
    <div className="smart:py-1">
      <SmartCrudFilterField {...props} />
    </div>
  );
}

// packages/crud/shell/angular/src/lib/components/filter/filter.component.ts
import { Component, Input, OnInit } from "@angular/core";

import {FieldType, IModelFilter} from "@smartsoft001/models";

import {ICrudFilter} from "../../models/interfaces";

@Component({
  selector: "smart-crud-filter",
  templateUrl: "./filter.component.html",
  styleUrls: ["./filter.component.scss"],
})
export class FilterComponent implements OnInit {
  FieldType = FieldType;

  @Input() item: IModelFilter;
  @Input() filter: ICrudFilter;

  constructor() {}

  ngOnInit(): void {}
}

<div class="smart:py-1">
  @switch ($safeNavigationMigration(item()?.fieldType)) {
    @case (FieldType.date) {
      <smart-crud-filter-date
        [item]="item()"
        [filter]="filter()"
      ></smart-crud-filter-date>
    }
    @case (FieldType.dateWithEdit) {
      <smart-crud-filter-date-with-edit
        [item]="item()"
        [filter]="filter()"
      ></smart-crud-filter-date-with-edit>
    }
    @case (FieldType.dateTime) {
      <smart-crud-filter-date-time
        [item]="item()"
        [filter]="filter()"
      ></smart-crud-filter-date-time>
    }
    @case (FieldType.radio) {
      <smart-crud-filter-radio
        [item]="item()"
        [filter]="filter()"
      ></smart-crud-filter-radio>
    }
    @case (FieldType.check) {
      <smart-crud-filter-check
        [item]="item()"
        [filter]="filter()"
      ></smart-crud-filter-check>
    }
    @case (FieldType.flag) {
      <smart-crud-filter-flag
        [item]="item()"
        [filter]="filter()"
      ></smart-crud-filter-flag>
    }
    @case (FieldType.int) {
      <smart-crud-filter-int
        [item]="item()"
        [filter]="filter()"
      ></smart-crud-filter-int>
    }
    @default {
      <smart-crud-filter-text
        [item]="item()"
        [filter]="filter()"
      ></smart-crud-filter-text>
    }
  }
</div>
