// docs/examples/react/src/crud/crud-facade.example.tsx
// #region usage
import { useEffect } from 'react';

import {
  CrudProvider,
  useCrudFacade,
  useCrudState,
} from '@smartsoft001/crud-shell-react';

import { Note, noteCrudConfig } from './crud-config.example';

function NoteTitles() {
  // The facade and the state of the nearest CrudProvider, already scoped to
  // the `entity` of its config.
  const facade = useCrudFacade<Note>();
  // `list` is undefined until the first read resolves.
  const notes = useCrudState<Note, Note[] | undefined>((state) => state.list);
  const loading = useCrudState<Note, boolean>((state) => !state.loaded);

  useEffect(() => {
    facade.read({});
  }, [facade]);

  return (
    <>
      {loading && <p>Loading notes…</p>}
      <ul>
        {(notes ?? []).map((note) => (
          <li key={note.id}>{note.title}</li>
        ))}
      </ul>
    </>
  );
}

export function NotesList() {
  return (
    <CrudProvider config={noteCrudConfig}>
      <NoteTitles />
    </CrudProvider>
  );
}
// #endregion

// docs/examples/angular/src/crud/crud-facade.example.ts
// #region usage
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  OnInit,
} from '@angular/core';

import { CrudFacade } from '@smartsoft001/crud-shell-angular';

import { Note } from './crud-config.example';

@Component({
  selector: 'docs-notes-list-example',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (facade.loading()) {
      <p>Loading notes…</p>
    }
    <ul>
      @for (note of notes(); track note.id) {
        <li>{{ note.title }}</li>
      }
    </ul>
  `,
})
export class NotesListComponent implements OnInit {
  // CrudFacade is provided by CrudModule.forFeature; its signals are already
  // scoped to the `entity` named in the config.
  readonly facade = inject(CrudFacade<Note>);

  // `list()` is undefined until the first read resolves.
  readonly notes = computed(() => this.facade.list() ?? []);

  ngOnInit(): void {
    this.facade.read({});
  }
}
// #endregion
