// packages/crud/shell/angular/src/lib/components/export/export.component.ts
import { Component } from '@angular/core';

import { ButtonComponent } from '@smartsoft001/angular';
import { IEntity } from '@smartsoft001/domain-core';

import { ExportBaseComponent } from './base/base.component';

@Component({
  selector: 'smart-crud-export',
  template: `
    <div class="smart:p-5">
      <p class="smart:my-2.5 smart:mx-0">
        <smart-button
          [options]="buttonExportCsvOptions"
          class="smart:w-full smart:block"
          >CSV</smart-button
        >
      </p>
      <p>
        <smart-button
          [options]="buttonExportXlsxOptions"
          class="smart:w-full smart:block"
          >XLSX</smart-button
        >
      </p>
    </div>
  `,
  imports: [ButtonComponent],
})
export class ExportComponent<
  T extends IEntity<string>,
> extends ExportBaseComponent<T> {}

<div class="smart-content">
    <p>
        <smart-button [options]="buttonExportCsvOptions">CSV</smart-button>
    </p>
    <p>
        <smart-button [options]="buttonExportXlsxOptions">XLSX</smart-button>
    </p>
</div>

// packages/crud/shell/react/src/lib/components/export/export.tsx
import { IEntity } from '@smartsoft001/domain-core';
import { SmartButton } from '@smartsoft001/react';

import { SmartCrudExportProps } from './export.types';
import { useCrudExport } from './use-crud-export';

/**
 * `<smart-crud-export>`: the CSV / XLSX buttons exporting the list of the
 * CRUD feature with its current filter (the Angular `ExportComponent`).
 */
export function SmartCrudExport<T extends IEntity<string>>(
  props: SmartCrudExportProps,
) {
  const { elementRef, buttonExportCsvOptions, buttonExportXlsxOptions } =
    useCrudExport<T>(props);

  return (
    <div ref={elementRef} className="smart:p-5">
      <p className="smart:my-2.5 smart:mx-0">
        <SmartButton
          options={buttonExportCsvOptions}
          className="smart:w-full smart:block"
        >
          CSV
        </SmartButton>
      </p>
      <p>
        <SmartButton
          options={buttonExportXlsxOptions}
          className="smart:w-full smart:block"
        >
          XLSX
        </SmartButton>
      </p>
    </div>
  );
}
