// docs/examples/react/src/components/detail/custom.example.tsx
// #region usage
import { Field, FieldType, Model } from '@smartsoft001/models';
import {
  IDetailOptions,
  SmartDetail,
  SmartDetailFieldProps,
  SmartProvider,
  useDetail,
} from '@smartsoft001/react';

/**
 * A custom renderer for one detail field, built on `useDetail`.
 *
 * The hook unwraps the item, the field key and its value from `options`;
 * `SmartDetail` passes the consumer's `className` on. Everything else is the
 * implementation's own markup.
 */
export function CustomDetail(props: SmartDetailFieldProps) {
  const { value } = useDetail(props);

  return (
    <p
      className={['docs-detail-text', props.className]
        .filter(Boolean)
        .join(' ')}
    >
      {String(value ?? '')}
    </p>
  );
}

@Model({})
class ApplicantModel {
  @Field({ details: true, type: FieldType.text })
  name = 'Margot Foster';
}

// <SmartDetail> picks the renderer by the field's `type`, so a custom one is
// registered per FieldType through `detailFieldComponents`. The entries are
// merged over the built-in map, so only the listed types change. A module
// constant: a new object on every render would change the context.
const detailFieldComponents = { [FieldType.text]: CustomDetail };

const options: IDetailOptions<ApplicantModel> = {
  key: 'name',
  options: { type: FieldType.text },
  item: new ApplicantModel(),
};

export function DetailCustomExample() {
  return (
    <SmartProvider detailFieldComponents={detailFieldComponents}>
      <SmartDetail
        type={ApplicantModel}
        options={options}
        className="docs-detail-text--demo"
      />
    </SmartProvider>
  );
}
// #endregion

// docs/examples/angular/src/components/detail/custom.example.ts
// #region usage
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  signal,
} from '@angular/core';

import {
  DetailBaseComponent,
  DetailComponent,
  DETAIL_FIELD_COMPONENTS_TOKEN,
  IDetailOptions,
} from '@smartsoft001/angular';
import { Field, FieldType, Model } from '@smartsoft001/models';

/**
 * A custom renderer for one detail field, built on `DetailBaseComponent`.
 *
 * The base supplies the `options` input (key, item signal, field metadata) and
 * the `class` input, and re-runs `afterSetOptionsHandler()` whenever the
 * options change. Everything else is the implementation's own template.
 */
@Component({
  selector: 'docs-custom-detail-text',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<p [class]="classes()">{{ value() }}</p>`,
})
export class CustomDetailTextComponent extends DetailBaseComponent<
  Record<string, unknown>
> {
  value = computed(() => {
    const options = this.options();
    const item = options?.item?.();
    if (!options || !item) return '';
    return String(item[options.key] ?? '');
  });

  // `cssClass` comes from the base (alias `class`): smart-detail forwards the
  // consumer's class to the field component.
  classes = computed(() =>
    ['docs-detail-text', this.cssClass()].filter(Boolean).join(' '),
  );
}

@Model({})
class ApplicantModel {
  @Field({ details: true, type: FieldType.text })
  name = 'Margot Foster';
}

/**
 * `<smart-detail>` chooses the renderer from the field's `type`, so a custom
 * implementation is registered per FieldType through
 * `DETAIL_FIELD_COMPONENTS_TOKEN`. Entries are merged over the built-in map,
 * so only the listed types change.
 */
@Component({
  selector: 'docs-detail-custom-example',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [DetailComponent],
  providers: [
    {
      provide: DETAIL_FIELD_COMPONENTS_TOKEN,
      useValue: { [FieldType.text]: CustomDetailTextComponent },
    },
  ],
  template: `
    <smart-detail
      [type]="type"
      [options]="options"
      [class]="'docs-detail-text--demo'"
    />
  `,
})
export class DetailCustomExampleComponent {
  type = ApplicantModel;

  options: IDetailOptions<ApplicantModel> = {
    key: 'name',
    options: { type: FieldType.text },
    item: signal(new ApplicantModel()),
  };
}
// #endregion
