// docs/examples/angular/src/components/grid-list/custom.example.ts
// #region usage
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ViewEncapsulation,
} from '@angular/core';

import {
  GRID_LIST_STANDARD_COMPONENT_TOKEN,
  GridListBaseComponent,
  GridListComponent,
  IGridListOptions,
} from '@smartsoft001/angular';

@Component({
  selector: 'docs-custom-grid-list',
  template: `
    <div [class]="containerClasses()">
      @if (options()?.title) {
        <h3 class="docs-grid-list__title">{{ options()?.title }}</h3>
      }

      <ul
        class="docs-grid-list__items"
        [attr.data-columns]="options()?.columns ?? null"
      >
        @for (item of options()?.items ?? []; track item.id ?? $index) {
          <li class="docs-grid-list__item">
            @if (item.imageUrl) {
              <img
                class="docs-grid-list__image"
                [src]="item.imageUrl"
                [attr.alt]="item.imageAlt ?? ''"
              />
            }
            @if (item.href) {
              <a class="docs-grid-list__link" [attr.href]="item.href">
                {{ item.title }}
              </a>
            } @else {
              <span class="docs-grid-list__label">{{ item.title }}</span>
            }
            @if (item.description) {
              <p class="docs-grid-list__description">{{ item.description }}</p>
            }
          </li>
        }
      </ul>
    </div>
  `,
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CustomGridListComponent extends GridListBaseComponent {
  containerClasses = computed(() => {
    const classes = ['docs-grid-list'];
    const extra = this.cssClass();
    if (extra) classes.push(extra);
    return classes.join(' ');
  });
}

@Component({
  selector: 'docs-grid-list-custom-example',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [GridListComponent],
  // The token swaps the standard grid list for the custom one everywhere
  // below this component, so consumers keep writing `<smart-grid-list>`.
  providers: [
    {
      provide: GRID_LIST_STANDARD_COMPONENT_TOKEN,
      useValue: CustomGridListComponent,
    },
  ],
  template: `<smart-grid-list [options]="options" />`,
})
export class GridListCustomExampleComponent {
  options: IGridListOptions = {
    title: 'Team',
    columns: 3,
    items: [
      {
        id: 'lindsay',
        title: 'Lindsay Walton',
        description: 'Front-end Developer',
        href: '/team/lindsay-walton',
      },
      { id: 'courtney', title: 'Courtney Henry', description: 'Designer' },
      { id: 'tom', title: 'Tom Cook', description: 'Director of Product' },
    ],
  };
}
// #endregion

// docs/examples/react/src/components/grid-list/custom.example.tsx
// #region usage
import {
  cn,
  IGridListOptions,
  SmartGridList,
  SmartGridListProps,
  SmartProvider,
} from '@smartsoft001/react';

export function CustomGridList({ options, className }: SmartGridListProps) {
  return (
    <div className={cn('docs-grid-list', className)}>
      {options?.title && (
        <h3 className="docs-grid-list__title">{options.title}</h3>
      )}

      <ul className="docs-grid-list__items" data-columns={options?.columns}>
        {(options?.items ?? []).map((item, index) => (
          <li key={item.id ?? index} className="docs-grid-list__item">
            {item.imageUrl && (
              <img
                className="docs-grid-list__image"
                src={item.imageUrl}
                alt={item.imageAlt ?? ''}
              />
            )}
            {item.href ? (
              <a className="docs-grid-list__link" href={item.href}>
                {item.title}
              </a>
            ) : (
              <span className="docs-grid-list__label">{item.title}</span>
            )}
            {item.description && (
              <p className="docs-grid-list__description">{item.description}</p>
            )}
          </li>
        ))}
      </ul>
    </div>
  );
}

// A module constant: a new object on every render would change the context.
const components = { 'grid-list': CustomGridList };

const options: IGridListOptions = {
  title: 'Team',
  columns: 3,
  items: [
    {
      id: 'lindsay',
      title: 'Lindsay Walton',
      description: 'Front-end Developer',
      href: '/team/lindsay-walton',
    },
    { id: 'courtney', title: 'Courtney Henry', description: 'Designer' },
    { id: 'tom', title: 'Tom Cook', description: 'Director of Product' },
  ],
};

export function GridListCustomExample() {
  // Every SmartGridList below the provider renders CustomGridList.
  return (
    <SmartProvider components={components}>
      <SmartGridList options={options} />
    </SmartProvider>
  );
}
// #endregion
