// packages/crud/shell/angular/src/lib/components/filters-config/filters-config.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  OnInit,
  Signal,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import { StyleService } from '@smartsoft001/angular';

import { CrudFacade } from '../../+state/crud.facade';
import { ICrudFilterQueryItem } from '../../models';

@Component({
  selector: 'smart-crud-filters-config',
  template: `
    @let query = this.query();
    @if (query && query.length) {
      <div class="smart:flex smart:flex-wrap smart:gap-2 smart:px-4 smart:py-2">
        @for (item of query; track item) {
          <button
            type="button"
            (click)="onRemoveQuery(item)"
            class="smart:inline-flex smart:items-center smart:gap-1 smart:rounded-full smart:border smart:border-gray-300 smart:bg-gray-50 smart:px-3 smart:py-1 smart:text-sm smart:text-gray-700 smart:hover:bg-gray-100"
            [attr.aria-label]="
              ('remove' | translate) + ' ' + ('MODEL.' + item.key | translate)
            "
          >
            <span
              >{{ 'MODEL.' + item.key | translate }} {{ item.type }}
              {{ item.value | translate }}</span
            >
            <span aria-hidden="true" class="smart:text-red-600">✕</span>
          </button>
        }
      </div>
    }
  `,
  imports: [TranslatePipe],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FiltersConfigComponent implements OnInit {
  private readonly facade = inject(CrudFacade<any>);
  private styleService = inject(StyleService);
  private elementRef = inject(ElementRef);

  query!: Signal<ICrudFilterQueryItem[]>;

  onRemoveQuery(item: ICrudFilterQueryItem): void {
    const filter = this.facade.filter();
    if (filter?.query) {
      const index = filter.query.indexOf(item);
      if (index > -1) {
        filter.query.splice(index, 1);
      }
    }
    this.facade.read(this.facade.filter());
  }

  ngOnInit(): void {
    this.styleService.init(this.elementRef);

    this.query = computed(() => {
      const filter = this.facade.filter();
      return filter?.query?.filter((i) => !i.hidden) || [];
    });
  }
}

@let query = this.query();
@if (query && query?.length) {
  <!--  <ion-toolbar>-->
  @for (item of query; track item) {
    <!--      <ion-chip (click)="onRemoveQuery(item)" color="medium" outline="true">-->
    <!--        <ion-icon name="filter-circle-outline" color="primary"></ion-icon>-->
    <!--        <ion-label>-->
    {{ 'MODEL.' + item.key | translate }} {{ item.type }}
    {{ item.value | translate }}
    <!--        </ion-label>-->
    <!--        <ion-icon name="close" color="danger"></ion-icon>-->
    <!--      </ion-chip>-->
  }
  <!--  </ion-toolbar>-->
}

// packages/crud/shell/react/src/lib/components/filters-config/filters-config.tsx
import { useMemo } from 'react';

import { useTranslate } from '@smartsoft001/react';
import type { SmartTranslateFn } from '@smartsoft001/react';

import { useCrudFacade } from '../../crud.context';
import { useCrudState } from '../../hooks';
import { ICrudFilterQueryItem } from '../../models';

// The Angular `{{ item.value | translate }}`: a text is translated, any other
// value is shown as it is.
function translateValue(t: SmartTranslateFn, value: unknown): string {
  if (value === null || value === undefined) return '';
  if (typeof value === 'string') return t(value);

  return String(value);
}

/**
 * `<smart-crud-filters-config>`: the active filters of the CRUD feature
 * (the visible items of `filter.query`) as chips; clicking a chip removes the
 * item and reads the list again. Render it inside `<CrudProvider>`.
 */
export function SmartCrudFiltersConfig() {
  const t = useTranslate();
  const facade = useCrudFacade();
  const filter = useCrudState((state) => state.filter);

  const query = useMemo<ICrudFilterQueryItem[]>(
    () => filter?.query?.filter((i) => !i.hidden) || [],
    [filter],
  );

  const onRemoveQuery = (item: ICrudFilterQueryItem): void => {
    const current = facade.filter;

    facade.read(
      current?.query
        ? { ...current, query: current.query.filter((i) => i !== item) }
        : current,
    );
  };

  if (!query.length) return null;

  return (
    <div className="smart:flex smart:flex-wrap smart:gap-2 smart:px-4 smart:py-2">
      {query.map((item, index) => (
        <button
          key={`${index}:${item.key}:${item.type}`}
          type="button"
          onClick={() => onRemoveQuery(item)}
          className="smart:inline-flex smart:items-center smart:gap-1 smart:rounded-full smart:border smart:border-gray-300 smart:bg-gray-50 smart:px-3 smart:py-1 smart:text-sm smart:text-gray-700 smart:hover:bg-gray-100"
          aria-label={t('remove') + ' ' + t('MODEL.' + item.key)}
        >
          <span>
            {t('MODEL.' + item.key)} {item.type} {translateValue(t, item.value)}
          </span>
          <span aria-hidden="true" className="smart:text-red-600">
            ✕
          </span>
        </button>
      ))}
    </div>
  );
}
