// packages/crud/shell/angular/src/lib/components/group/group.component.ts
import { NgClass } from '@angular/common';
import { Component } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import {
  // TODO: AccordionComponent moved to @smartsoft001-pro/angular (FRA-101)
  // AccordionBodyComponent,
  // AccordionComponent,
  // AccordionHeaderComponent,
  ListComponent,
} from '@smartsoft001/angular';
import { IEntity } from '@smartsoft001/domain-core';

import { GroupBaseComponent } from './base/base.component';

@Component({
  selector: 'smart-crud-group',
  template: `
    <!-- TODO: AccordionComponent moved to @smartsoft001-pro/angular (FRA-101)
    @for (item of groups(); track item.key) {
      <smart-accordion
        [show]="item.show || false"
        (showChange)="change($event, item)"
      >
        <smart-accordion-header [ngClass]="{ 'font-bold': item.show }">
          {{ item.text | translate }}
        </smart-accordion-header>
        <smart-accordion-body>
          @if (item.show && !item.children && listOptions()) {
            <smart-list [options]="listOptions()!"></smart-list>
          }
          @if (item.children) {
            <div style="margin-left: 50px">
              <smart-crud-group
                [groups]="item.children"
                [listOptions]="listOptions()"
              ></smart-crud-group>
            </div>
          }
        </smart-accordion-body>
      </smart-accordion>
    }
    -->

    <!-- TODO: remove this template after moving to @smartsoft001-pro/angular (FRA-101) -->
    @for (item of groups(); track item.key) {
      <div (click)="change(!item.show, item)">
        {{ item.text | translate }}
      </div>
      @if (item.show && !item.children && listOptions()) {
        <smart-list [options]="listOptions()!"></smart-list>
      }
      @if (item.children) {
        <div style="margin-left: 50px">
          <smart-crud-group
            [groups]="item.children"
            [listOptions]="listOptions()"
          ></smart-crud-group>
        </div>
      }
    }
  `,
  imports: [
    // TODO: AccordionComponent moved to @smartsoft001-pro/angular (FRA-101)
    // AccordionComponent,
    // AccordionHeaderComponent,
    // AccordionBodyComponent,
    ListComponent,
    NgClass,
    TranslatePipe,
  ],
})
export class GroupComponent<
  T extends IEntity<string>,
> extends GroupBaseComponent<T> {}

<smart-accordion *ngFor="let item of groups" [(show)]="item.show" (showChange)="change($event, item)">
    <smart-accordion-header [ngClass]="{ 'accordion-show': item.show }">{{ item.text | translate }}</smart-accordion-header>
    <smart-accordion-body>
        <smart-list *ngIf="item.show && !item.children && listOptions" [options]="listOptions"></smart-list>
        <div *ngIf="item.children" style="margin-left: 50px">
            <smart-crud-group [groups]="item.children" [listOptions]="listOptions"></smart-crud-group>
        </div>
    </smart-accordion-body>
</smart-accordion>
<br/><br/><br/>

// packages/crud/shell/react/src/lib/components/group/group.tsx
import { IEntity } from '@smartsoft001/domain-core';
import { cn, SmartList, useTranslate } from '@smartsoft001/react';

import { SmartCrudGroupProps } from './group.types';
import { useCrudGroup } from './use-crud-group';

/**
 * `<smart-crud-group>`: the list grouped by `groups` (the Angular
 * `GroupComponent`), each group an accessible disclosure — a button with
 * `aria-expanded` / `aria-controls` and its region. An open group shows the
 * list with `listOptions`, or its `children` groups. Render it inside
 * `<CrudProvider>`.
 */
export function SmartCrudGroup<T extends IEntity<string>>(
  props: SmartCrudGroupProps<T>,
) {
  const t = useTranslate();
  const { groups, listOptions, change } = useCrudGroup<T>(props);

  return (
    <>
      {groups?.map((item) => (
        <div key={item.key} className="smart:border-b smart:border-gray-200">
          <button
            type="button"
            onClick={() => change(!item.show, item)}
            aria-expanded={item.show || false}
            aria-controls={'smart-crud-group-' + item.key}
            className={cn(
              'smart:flex smart:w-full smart:items-center smart:justify-between smart:py-3 smart:text-left smart:text-sm',
              item.show && 'smart:font-bold',
            )}
          >
            <span>{t(item.text)}</span>
            <span aria-hidden="true" className="smart:text-gray-500">
              {item.show ? '▾' : '▸'}
            </span>
          </button>
          {item.show && (
            <div id={'smart-crud-group-' + item.key} className="smart:pb-3">
              {!item.children && listOptions && (
                <SmartList options={listOptions} />
              )}
              {item.children && (
                <div className="smart:ml-12">
                  <SmartCrudGroup
                    groups={item.children}
                    listOptions={listOptions}
                  />
                </div>
              )}
            </div>
          )}
        </div>
      ))}
    </>
  );
}
