// docs/examples/angular/src/components/vertical-navigation/custom.example.ts
// #region usage
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  signal,
  ViewEncapsulation,
} from '@angular/core';

import {
  IVerticalNavOptions,
  VERTICAL_NAVIGATION_STANDARD_COMPONENT_TOKEN,
  VerticalNavigationBaseComponent,
  VerticalNavigationComponent,
} from '@smartsoft001/angular';

@Component({
  selector: 'docs-custom-vertical-navigation',
  template: `
    <nav
      [class]="containerClasses()"
      [attr.aria-label]="options()?.ariaLabel ?? 'Sidebar'"
    >
      <!--
        The base normalizes options.items and options.groups into one list of
        groups, so the implementation only has to render groups.
      -->
      @for (group of groups(); track group.id ?? $index) {
        <div class="docs-vertical-nav__group">
          @if (group.title) {
            <div class="docs-vertical-nav__group-title">{{ group.title }}</div>
          }
          <ul role="list">
            @for (item of group.items; track item.id) {
              <li [class]="itemClasses(item.current)">
                @if (item.href) {
                  <a
                    [href]="item.href"
                    [attr.aria-current]="item.current ? 'page' : null"
                  >
                    @if (item.initial) {
                      <span class="docs-vertical-nav__initial">
                        {{ item.initial }}
                      </span>
                    }
                    <span>{{ item.label ?? item.id }}</span>
                    @if (item.badge !== undefined && item.badge !== null) {
                      <span class="docs-vertical-nav__badge">
                        {{ item.badge }}
                      </span>
                    }
                  </a>
                } @else {
                  <button type="button" (click)="onItemClick(item.id)">
                    {{ item.label ?? item.id }}
                  </button>
                }
              </li>
            }
          </ul>
        </div>
      }
    </nav>
  `,
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CustomVerticalNavigationComponent extends VerticalNavigationBaseComponent {
  groups = computed(() => this.resolvedGroups());

  containerClasses = computed(() =>
    [
      'docs-vertical-nav',
      `docs-vertical-nav--${this.options()?.layout ?? 'simple'}`,
      this.cssClass(),
    ]
      .filter(Boolean)
      .join(' '),
  );

  protected itemClasses(current: boolean | undefined): string {
    return current
      ? 'docs-vertical-nav__item docs-vertical-nav__item--current'
      : 'docs-vertical-nav__item';
  }

  protected onItemClick(itemId: string): void {
    this.itemClick.emit({ itemId });
  }
}

@Component({
  selector: 'docs-vertical-navigation-custom-example',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [VerticalNavigationComponent],
  // The token swaps the standard navigation for the custom one everywhere below
  // this component, so consumers keep writing `<smart-vertical-navigation>`.
  providers: [
    {
      provide: VERTICAL_NAVIGATION_STANDARD_COMPONENT_TOKEN,
      useValue: CustomVerticalNavigationComponent,
    },
  ],
  // The wrapper re-emits `itemClick` of the custom component.
  template: `
    <smart-vertical-navigation
      [options]="options"
      (itemClick)="lastItem.set($event.itemId)"
    />
    @if (lastItem()) {
      <p>Last clicked item: {{ lastItem() }}</p>
    }
  `,
})
export class VerticalNavigationCustomExampleComponent {
  readonly lastItem = signal<string | null>(null);

  // `items` and `groups` can be combined: the base puts the loose items in a
  // first, untitled group and appends the explicit groups after them.
  options: IVerticalNavOptions = {
    // The built-in implementations do not read `layout`; this custom one turns
    // it into a class.
    layout: 'with-badges',
    ariaLabel: 'Sidebar',
    items: [
      { id: 'dashboard', label: 'Dashboard', href: '#dashboard' },
      { id: 'team', label: 'Team', href: '#team', current: true, badge: 5 },
      { id: 'calendar', label: 'Calendar', href: '#calendar' },
    ],
    groups: [
      {
        id: 'projects',
        title: 'Projects',
        items: [
          {
            id: 'website',
            label: 'Website redesign',
            href: '#website',
            initial: 'W',
          },
          { id: 'new-project', label: 'New project' },
        ],
      },
    ],
  };
}
// #endregion

// docs/examples/react/src/components/vertical-navigation/custom.example.tsx
// #region usage
import { useState } from 'react';

import {
  IVerticalNavOptions,
  SmartProvider,
  SmartVerticalNavigation,
  SmartVerticalNavigationProps,
  useVerticalNavigation,
} from '@smartsoft001/react';

export function CustomVerticalNavigation(props: SmartVerticalNavigationProps) {
  const { options, className } = props;
  // useVerticalNavigation normalises options.items and options.groups into one
  // list of groups and reports clicks through onItemClick.
  const { groups, itemClick } = useVerticalNavigation(props);
  const containerClasses = [
    'docs-vertical-nav',
    `docs-vertical-nav--${options?.layout ?? 'simple'}`,
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <nav
      className={containerClasses}
      aria-label={options?.ariaLabel ?? 'Sidebar'}
    >
      {groups.map((group, index) => (
        <div key={group.id ?? index} className="docs-vertical-nav__group">
          {group.title && (
            <div className="docs-vertical-nav__group-title">{group.title}</div>
          )}
          <ul role="list">
            {group.items.map((item) => (
              <li
                key={item.id}
                className={
                  item.current
                    ? 'docs-vertical-nav__item docs-vertical-nav__item--current'
                    : 'docs-vertical-nav__item'
                }
              >
                {item.href ? (
                  <a
                    href={item.href}
                    aria-current={item.current ? 'page' : undefined}
                  >
                    {item.initial && (
                      <span className="docs-vertical-nav__initial">
                        {item.initial}
                      </span>
                    )}
                    <span>{item.label ?? item.id}</span>
                    {item.badge !== undefined && item.badge !== null && (
                      <span className="docs-vertical-nav__badge">
                        {item.badge}
                      </span>
                    )}
                  </a>
                ) : (
                  <button type="button" onClick={() => itemClick(item.id)}>
                    {item.label ?? item.id}
                  </button>
                )}
              </li>
            ))}
          </ul>
        </div>
      ))}
    </nav>
  );
}

// A module constant: a new object on every render would change the context.
const components = { 'vertical-navigation': CustomVerticalNavigation };

// `items` and `groups` can be combined: the hook puts the loose items in a
// first, untitled group and appends the explicit groups after them.
const options: IVerticalNavOptions = {
  // The built-in implementations do not read `layout`; this custom one turns it
  // into a class.
  layout: 'with-badges',
  ariaLabel: 'Sidebar',
  items: [
    { id: 'dashboard', label: 'Dashboard', href: '#dashboard' },
    { id: 'team', label: 'Team', href: '#team', current: true, badge: 5 },
    { id: 'calendar', label: 'Calendar', href: '#calendar' },
  ],
  groups: [
    {
      id: 'projects',
      title: 'Projects',
      items: [
        {
          id: 'website',
          label: 'Website redesign',
          href: '#website',
          initial: 'W',
        },
        { id: 'new-project', label: 'New project' },
      ],
    },
  ],
};

// Every <SmartVerticalNavigation> below the provider renders
// CustomVerticalNavigation.
export function VerticalNavigationCustomExample() {
  const [lastItem, setLastItem] = useState<string | null>(null);

  return (
    <SmartProvider components={components}>
      <SmartVerticalNavigation
        options={options}
        onItemClick={({ itemId }) => setLastItem(itemId)}
      />
      {lastItem && <p>Last clicked item: {lastItem}</p>}
    </SmartProvider>
  );
}
// #endregion
