// docs/examples/angular/src/crud/crud-list-page.example.ts
// #region usage
import { ChangeDetectionStrategy, Component } from '@angular/core';

import { ListComponent } from '@smartsoft001/crud-shell-angular';

// With `routing: false` the app places the generated pages itself. The page
// takes no inputs: it reads everything from the CrudFullConfig that
// CrudModule.forFeature provided for this feature.
@Component({
  selector: 'docs-notes-page-example',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ListComponent],
  template: `<smart-crud-list-page></smart-crud-list-page>`,
})
export class NotesPageComponent {}
// #endregion

// docs/examples/react/src/crud/crud-list-page.example.tsx
// #region usage
import {
  CrudProvider,
  SmartCrudListPage,
} from '@smartsoft001/crud-shell-react';

import { noteCrudConfig } from './crud-config.example';

// An application with a router of its own renders the page on its list
// route. The page takes no configuration props: it reads the CrudFullConfig
// of the CrudProvider around it. `basePath` is where the add button
// (`/notes/add`) and the row links (`/notes/:id`) lead.
export function NotesListRoute() {
  return (
    <CrudProvider config={noteCrudConfig}>
      <SmartCrudListPage basePath="/notes" />
    </CrudProvider>
  );
}
// #endregion
