// packages/shared/angular/src/lib/components/list/list.component.ts
import { NgComponentOutlet } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  input,
  signal,
  Signal,
  Type,
  ViewEncapsulation,
  WritableSignal,
} from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import * as _ from 'lodash';

import { IEntity } from '@smartsoft001/domain-core';
import {
  getModelFieldsWithOptions,
  IFieldListMetadata,
} from '@smartsoft001/models';

import { IListInternalOptions, IListOptions, ListMode } from '../../models';
import { HardwareService } from '../../services';
import { LIST_MODE_COMPONENTS_TOKEN } from '../../shared.inectors';
import { LoaderComponent } from '../loader';
import { ListBaseComponent } from './base/base.component';
import { ListDesktopComponent } from './desktop/desktop.component';
import { ListMasonryGridComponent } from './masonry-grid/masonry-grid.component';
import { ListMobileComponent } from './mobile/mobile.component';

const baseMap: Partial<Record<ListMode, Type<ListBaseComponent<any>>>> = {
  [ListMode.desktop]: ListDesktopComponent,
  [ListMode.mobile]: ListMobileComponent,
  [ListMode.masonryGrid]: ListMasonryGridComponent,
};

@Component({
  selector: 'smart-list',
  templateUrl: './list.component.html',
  encapsulation: ViewEncapsulation.None,
  imports: [NgComponentOutlet, TranslatePipe, LoaderComponent],
  host: { class: 'smart:contents' },
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ListComponent<T extends IEntity<string>> {
  private hardwareService = inject(HardwareService);
  private extendMap = inject(LIST_MODE_COMPONENTS_TOKEN, { optional: true });

  private _options: WritableSignal<IListInternalOptions<T>> = signal(
    {} as IListInternalOptions<T>,
  );

  ListMode = ListMode;

  options = input.required<IListOptions<T>>();
  cssClass = input<string>('', { alias: 'class' });

  get internalOptions(): IListInternalOptions<T> {
    return this._options();
  }

  mode: Signal<ListMode> = computed(
    () =>
      this._options()?.mode ??
      (this.hardwareService.isMobile ? ListMode.mobile : ListMode.desktop),
  );

  componentType = computed(() => {
    const map = { ...baseMap, ...(this.extendMap ?? {}) };
    return map[this.mode()] ?? ListDesktopComponent;
  });

  componentInputs = computed(() => ({
    options: this._options(),
    class: this.cssClass(),
  }));

  constructor() {
    effect(() => {
      const options = this.options();
      this._options.set({
        ...options,
        fields: _.sortBy(
          getModelFieldsWithOptions(new (options as any).type())?.filter(
            (item) => item?.options?.list,
          ),
          (item) => (item?.options?.list as IFieldListMetadata).order,
        ),
      });
    });
  }
}

@if (template() === 'default') {
  @switch (mode()) {
    @case (ListMode.desktop) {
      <smart-list-desktop [options]="internalOptions"></smart-list-desktop>
    }
    @case (ListMode.mobile) {
      <smart-list-mobile [options]="internalOptions"></smart-list-mobile>
    }
    @case (ListMode.masonryGrid) {
      <smart-list-masonry-grid
        [options]="internalOptions"
      ></smart-list-masonry-grid>
    }
  }

  <!--  <ion-row>-->
  <!--    <ion-col></ion-col>-->
  <!--    <ion-col size="auto">-->
  @let loading = internalOptions?.provider?.loading();
  <smart-loader [show]="loading ?? false"></smart-loader>
  @if (!loading && !internalOptions.provider.list()?.length) {
    <h2>
      <br />
      {{ 'noResults' | translate }}
    </h2>
  }
  <!--    </ion-col>-->
  <!--    <ion-col></ion-col>-->
  <!--  </ion-row>-->

  <ng-container [ngTemplateOutlet]="contentTpl"></ng-container>
}

<ng-template #contentTpl>
  <ng-content></ng-content>
</ng-template>
<div class="dynamic-content"></div>

// packages/shared/react/src/lib/components/list/list.tsx
import { useMemo } from 'react';
import type { ComponentType } from 'react';

import { IEntity } from '@smartsoft001/domain-core';
import {
  getModelFieldsWithOptions,
  IFieldListMetadata,
  IFieldOptions,
} from '@smartsoft001/models';

import { SmartListDesktop } from './desktop/list-desktop';
import { SmartListModeProps, SmartListProps } from './list.types';
import { SmartListMasonryGrid } from './masonry-grid/list-masonry-grid';
import { SmartListMobile } from './mobile/list-mobile';
import { IListInternalOptions, ListMode } from '../../models';
import {
  useListModeComponents,
  useSmartComponent,
  useTranslate,
} from '../../providers/hooks';
import { SmartLoader } from '../loader/loader';

type ListField = { key: string; options: IFieldOptions };

const LIST_MODE_COMPONENTS: Partial<
  Record<ListMode, ComponentType<SmartListModeProps<IEntity<string>>>>
> = {
  [ListMode.desktop]: SmartListDesktop,
  [ListMode.mobile]: SmartListMobile,
  [ListMode.masonryGrid]: SmartListMasonryGrid,
};

/** Ascending `list.order`, the fields without one last (lodash `sortBy`). */
function compareOrder(a?: number, b?: number): number {
  if (a === b) return 0;
  if (a === undefined) return 1;
  if (b === undefined) return -1;

  return a - b;
}

/** The fields of the model with `list` options, sorted by `list.order`. */
function getListFields(type: any): ListField[] {
  const fields =
    getModelFieldsWithOptions(new type())?.filter(
      (item) => item?.options?.list,
    ) ?? [];

  return [...fields].sort((a, b) =>
    compareOrder(
      (a.options.list as IFieldListMetadata).order,
      (b.options.list as IFieldListMetadata).order,
    ),
  );
}

/**
 * `<smart-list>`: resolves the list `fields` of `options.type` (the fields
 * with `list` options, sorted by `list.order`) and renders the
 * implementation of `options.mode` (desktop by default): the one registered
 * in `listModeComponents` on `SmartProvider` (the Angular
 * `LIST_MODE_COMPONENTS_TOKEN`, e.g. `LIST_PRESET_MODE_COMPONENTS`), else
 * `SmartListDesktop` / `SmartListMobile` / `SmartListMasonryGrid`. A
 * component registered as `components.list` replaces it for every mode.
 *
 * Below it: the loader while `provider.loading`, and "no results" for an
 * empty list. (The Angular `HardwareService.isMobile` that picked the mobile
 * mode without `options.mode` is always `false`, so desktop is the default.)
 */
export function SmartList<T extends IEntity<string>>({
  options,
  className = '',
}: SmartListProps<T>) {
  const t = useTranslate();
  const modeComponents = useListModeComponents(LIST_MODE_COMPONENTS);
  const type = options.type;

  const fields = useMemo(() => getListFields(type), [type]);

  const internalOptions = useMemo<IListInternalOptions<T>>(
    () => ({ ...options, fields }),
    [options, fields],
  );

  const mode = internalOptions.mode ?? ListMode.desktop;
  const ModeComponent = useSmartComponent<SmartListModeProps<T>>(
    'list',
    modeComponents[mode] ?? SmartListDesktop,
  );
  const loading = internalOptions.provider?.loading;

  return (
    <>
      <ModeComponent options={internalOptions} className={className} />
      <SmartLoader show={loading ?? false} />
      {!loading && !internalOptions.provider?.list?.length ? (
        <h2 className="smart:mt-4 smart:text-center smart:text-gray-500 smart:dark:text-gray-400">
          {t('noResults')}
        </h2>
      ) : null}
    </>
  );
}
