// packages/crud/shell/react/src/lib/components/multiselect/multiselect.tsx
import { useMemo } from 'react';

import { IEntity } from '@smartsoft001/domain-core';
import { SmartButton, SmartForm, useTranslate } from '@smartsoft001/react';

import { useCrudMultiselect } from './use-crud-multiselect';
import { getCrudFormOptions } from '../../factories/form-options';

/**
 * `<smart-crud-multiselect>`: the panel of the items selected in the list
 * (the Angular `MultiselectComponent`), opened in the end menu. A header
 * with the count and a close button, the `config.list.components.multi`
 * component with the selected `items`, and the `multiUpdate` form of the
 * model with the button applying it to every selected item. Render it inside
 * `<CrudProvider>`.
 */
export function SmartCrudMultiselect<T extends IEntity<string>>() {
  const t = useTranslate();
  const {
    config,
    list,
    item,
    showForm,
    lock,
    valid,
    buttonOptions,
    onClose,
    onPartialChange,
    onValidChange,
  } = useCrudMultiselect<T>();

  const Multi = config?.list?.components?.multi;

  // The Angular `item | smartFormOptions: 'multiUpdate' : config.type`.
  const formOptions = useMemo(
    () => getCrudFormOptions(item, 'multiUpdate', config.type),
    [item, config.type],
  );

  return (
    <>
      <header className="smart:flex smart:items-center smart:justify-between smart:border-b smart:border-gray-200 smart:px-4 smart:py-3">
        <h2 className="smart:text-lg smart:font-semibold smart:text-gray-900">
          {t('selected')}: {list.length}
        </h2>
        <button
          type="button"
          onClick={onClose}
          aria-label="close"
          className="smart:rounded smart:p-1 smart:text-gray-500 smart:hover:bg-gray-100"
        >
          ✕
        </button>
      </header>

      {Multi && (
        <div>
          <Multi items={list} />
        </div>
      )}

      {showForm && item && formOptions && (
        <div>
          <SmartForm
            options={formOptions}
            onValuePartialChange={(changes) => onPartialChange(changes, list)}
            onValidChange={onValidChange}
          />

          <SmartButton
            className="smart:float-right"
            disabled={lock || !valid}
            options={buttonOptions}
          >
            {t('change')}
          </SmartButton>
        </div>
      )}
    </>
  );
}

// packages/crud/shell/angular/src/lib/components/multiselect/multiselect.component.ts
import { NgComponentOutlet } from '@angular/common';
import { Component, computed, inject, Signal } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import * as _ from 'lodash';
import { DynamicIoDirective } from 'ng-dynamic-component';

import {
  ButtonComponent,
  FormComponent,
  IButtonOptions,
  MenuService,
} from '@smartsoft001/angular';
import { IEntity } from '@smartsoft001/domain-core';
import {
  getModelFieldsWithOptions,
  IFieldEditMetadata,
} from '@smartsoft001/models';

import { CrudFacade } from '../../+state/crud.facade';
import { CrudFullConfig } from '../../crud.config';
import { FormOptionsPipe } from '../../pipes';

@Component({
  selector: 'smart-crud-multiselect',
  templateUrl: './multiselect.component.html',
  imports: [
    TranslatePipe,
    NgComponentOutlet,
    DynamicIoDirective,
    FormOptionsPipe,
    FormComponent,
    ButtonComponent,
  ],
})
export class MultiselectComponent<T extends IEntity<string>> {
  private facade = inject(CrudFacade<T>);
  public config = inject(CrudFullConfig<T>);
  private menuService = inject(MenuService);

  private _list!: Array<T>;
  private _changes!: Partial<T>;

  item!: T;
  valid!: boolean;
  buttonOptions: IButtonOptions = {
    click: async () => {
      const result = this._list.map((item) => {
        return {
          ...this._changes,
          id: item.id,
        };
      });

      this.facade.updatePartialMany(result);
      await this.menuService.closeEnd();
    },
    confirm: true,
  };
  lock!: boolean;
  showForm = false;

  list!: Signal<T[]>;

  constructor() {
    this.list = computed(() => {
      const list = this.facade.multiSelected() || [];
      this.lock = true;
      const model = new this.config.type();

      const fieldsWithOptions = getModelFieldsWithOptions(model)?.filter(
        (f) => (f.options.update as IFieldEditMetadata)?.multi,
      );

      this.showForm = !!fieldsWithOptions.length;

      fieldsWithOptions.forEach(({ key }) => {
        const uniques = _.uniq(list.map((i) => i[key]));

        if (uniques.length === 1) {
          model[key] = uniques[0];
        }
      });

      this.item = model;

      return list;
    });
  }

  async onClose(): Promise<void> {
    await this.menuService.closeEnd();
  }

  onPartialChange(changes: Partial<T>, list: Array<T>) {
    this.lock = false;
    this._list = list;
    this._changes = changes;
  }

  onValidChange(valid: boolean) {
    this.valid = valid;
  }
}

@let list = this.list();
@if (list) {
  <header
    class="smart:flex smart:items-center smart:justify-between smart:border-b smart:border-gray-200 smart:px-4 smart:py-3"
  >
    <h2 class="smart:text-lg smart:font-semibold smart:text-gray-900">
      {{ 'selected' | translate }}: {{ list.length }}
    </h2>
    <button
      type="button"
      (click)="onClose()"
      aria-label="close"
      class="smart:rounded smart:p-1 smart:text-gray-500 smart:hover:bg-gray-100"
    >
      ✕
    </button>
  </header>

  @if (config?.list?.components?.multi) {
    <div>
      <ng-template
        [ngComponentOutlet]="
          $safeNavigationMigration(config?.list?.components?.multi)
        "
        [ndcDynamicInputs]="{ items: list }"
      ></ng-template>
    </div>
  }

  @if (showForm && item) {
    <div>
      <smart-form
        [options]="item | smartFormOptions: 'multiUpdate' : config.type"
        (valuePartialChange)="onPartialChange($event, list)"
        (validChange)="onValidChange($event)"
      ></smart-form>

      <smart-button
        class="smart:float-right"
        [disabled]="lock || !valid"
        [options]="buttonOptions"
      >
        {{ 'change' | translate }}
      </smart-button>
    </div>
  }
}
