// docs/examples/angular/src/components/calendar/custom.example.ts
// #region usage
import { DatePipe } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ViewEncapsulation,
} from '@angular/core';

import {
  CalendarBaseComponent,
  CalendarComponent,
  CALENDAR_STANDARD_COMPONENT_TOKEN,
  ICalendarEvent,
} from '@smartsoft001/angular';

@Component({
  selector: 'docs-custom-calendar',
  imports: [DatePipe],
  template: `
    <div [class]="containerClasses()">
      @if (showToolbar()) {
        <div class="docs-calendar__toolbar">
          <button
            type="button"
            class="docs-calendar__prev"
            (click)="prevPeriod()"
          >
            Previous
          </button>
          <h2 class="docs-calendar__title">
            {{ reference() | date: 'LLLL yyyy' }}
          </h2>
          <button
            type="button"
            class="docs-calendar__today"
            (click)="goToToday()"
          >
            Today
          </button>
          <button
            type="button"
            class="docs-calendar__next"
            (click)="nextPeriod()"
          >
            Next
          </button>
        </div>
      }

      <div class="docs-calendar__grid">
        @for (week of monthGrid(); track $index) {
          <div class="docs-calendar__week">
            @for (cell of week; track cell.date.getTime()) {
              <button
                type="button"
                class="docs-calendar__day"
                [class.docs-calendar__day--outside]="!cell.isCurrentMonth"
                [attr.data-today]="cell.isToday ? 'true' : null"
                [attr.data-selected]="cell.isSelected ? 'true' : null"
                (click)="selectDay(cell.date)"
              >
                {{ cell.date.getDate() }}

                @for (event of eventsForDay(cell.date); track event.id) {
                  <span class="docs-calendar__event">{{ event.title }}</span>
                }
              </button>
            }
          </div>
        }
      </div>
    </div>
  `,
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CustomCalendarComponent extends CalendarBaseComponent {
  containerClasses = computed(() =>
    ['docs-calendar', this.cssClass()].filter(Boolean).join(' '),
  );
}

@Component({
  selector: 'docs-calendar-custom-example',
  imports: [CalendarComponent],
  providers: [
    {
      provide: CALENDAR_STANDARD_COMPONENT_TOKEN,
      useValue: CustomCalendarComponent,
    },
  ],
  template: `
    <smart-calendar [referenceDate]="referenceDate" [events]="events" />
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CalendarCustomExampleComponent {
  referenceDate = new Date(2026, 0, 1);

  // The standard and the preset never render `title`; this implementation does.
  events: ICalendarEvent[] = [
    {
      id: 'review',
      title: 'Design review',
      start: new Date(2026, 0, 15, 10, 0),
    },
  ];
}
// #endregion

// docs/examples/react/src/components/calendar/custom.example.tsx
// #region usage
import {
  ICalendarEvent,
  SmartCalendar,
  SmartCalendarProps,
  SmartProvider,
  useCalendar,
} from '@smartsoft001/react';

export function CustomCalendar(props: SmartCalendarProps) {
  const {
    showToolbar,
    reference,
    monthGrid,
    eventsForDay,
    selectDay,
    goToToday,
    prevPeriod,
    nextPeriod,
  } = useCalendar(props);

  return (
    <div
      className={['docs-calendar', props.className].filter(Boolean).join(' ')}
    >
      {showToolbar && (
        <div className="docs-calendar__toolbar">
          <button
            type="button"
            className="docs-calendar__prev"
            onClick={prevPeriod}
          >
            Previous
          </button>
          <h2 className="docs-calendar__title">
            {reference.toLocaleDateString('en-US', {
              month: 'long',
              year: 'numeric',
            })}
          </h2>
          <button
            type="button"
            className="docs-calendar__today"
            onClick={goToToday}
          >
            Today
          </button>
          <button
            type="button"
            className="docs-calendar__next"
            onClick={nextPeriod}
          >
            Next
          </button>
        </div>
      )}

      <div className="docs-calendar__grid">
        {monthGrid.map((week, index) => (
          <div key={index} className="docs-calendar__week">
            {week.map((cell) => (
              <button
                key={cell.date.getTime()}
                type="button"
                className={
                  cell.isCurrentMonth
                    ? 'docs-calendar__day'
                    : 'docs-calendar__day docs-calendar__day--outside'
                }
                data-today={cell.isToday ? 'true' : undefined}
                data-selected={cell.isSelected ? 'true' : undefined}
                onClick={() => selectDay(cell.date)}
              >
                {cell.date.getDate()}

                {eventsForDay(cell.date).map((event) => (
                  <span key={event.id} className="docs-calendar__event">
                    {event.title}
                  </span>
                ))}
              </button>
            ))}
          </div>
        ))}
      </div>
    </div>
  );
}

// A module constant: a new object on every render would change the context.
const components = { calendar: CustomCalendar };

const referenceDate = new Date(2026, 0, 1);

// The standard and the preset never render `title`; this implementation does.
const events: ICalendarEvent[] = [
  {
    id: 'review',
    title: 'Design review',
    start: new Date(2026, 0, 15, 10, 0),
  },
];

export function CalendarCustomExample() {
  return (
    <SmartProvider components={components}>
      <SmartCalendar referenceDate={referenceDate} events={events} />
    </SmartProvider>
  );
}
// #endregion
