// packages/crud/shell/react/src/lib/components/filters/filters.tsx
import { IEntity } from '@smartsoft001/domain-core';
import { useTranslate } from '@smartsoft001/react';

import { SmartCrudFiltersProps } from './filters.types';
import { useCrudFilters } from './use-crud-filters';
import { SmartCrudFilter } from '../filter/filter';

/**
 * `<smart-crud-filters>`: the filters panel of the CRUD feature (the Angular
 * `FiltersComponent`), opened in the end menu — a header with the title and
 * a close button (unless `hideMenu`), then a `SmartCrudFilter` for every
 * filter of the model: the `filters` of `@Model` and the fields with
 * `list.filter`. Render it inside `<CrudProvider>`.
 */
export function SmartCrudFilters<T extends IEntity<string>>(
  props: SmartCrudFiltersProps,
) {
  const t = useTranslate();
  const { elementRef, hideMenu, list, filter, onClose } =
    useCrudFilters<T>(props);

  return (
    <div ref={elementRef} className="smart:flex smart:h-full smart:flex-col">
      {!hideMenu && (
        <header className="smart:flex smart:items-center smart:justify-between smart:border-b smart:border-gray-200 smart:px-4 smart:py-3">
          <h2 className="smart:text-lg smart:font-semibold smart:text-gray-900">
            {t('filters')}
          </h2>
          <button
            type="button"
            onClick={onClose}
            aria-label="close"
            className="smart:rounded smart:p-1 smart:text-gray-500 smart:hover:bg-gray-100"
          >
            ✕
          </button>
        </header>
      )}
      <div className="smart:flex-1 smart:space-y-4 smart:overflow-y-auto smart:px-4 smart:py-3">
        {list.map((item, index) => (
          <SmartCrudFilter
            key={`${index}:${item.key}`}
            item={item}
            filter={filter}
          />
        ))}
      </div>
    </div>
  );
}

// packages/crud/shell/angular/src/lib/components/filters/filters.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';

import { IEntity } from '@smartsoft001/domain-core';

import { FilterComponent } from '../filter';
import { FiltersBaseComponent } from './base/base.component';

/**
 * This component is only to use in crud module
 * @requires CrudModule
 * @example
 *
 * html: <smart-crud-filters></smart-crud-filters>
 *
 * use on the model:
 * @Model({
    titleKey: 'body',
    filters: [
        {
            label: 'testNegation',
            key: 'body',
            type: '!=',
        },
        {
            label: 'fromDate',
            key: 'createDate',
            type: '<=',
            fieldType: FieldType.dateWithEdit
        },
        {
            label: 'select',
            key: 'type',
            type: '=',
            fieldType: FieldType.radio,
            possibilities$: of([
                {
                    id: 1, text: 'Test 1'
                },
                {
                    id: 2, text: 'Test 2'
                }
            ])
        }
    ]
})
 *
 * use on the field (list.filter property):
 * @Field({
        create: modifyMetdata,
        update: {
            ...modifyMetdata,
            multi: true
        },
        type: FieldType.longText,
        details: true,
        list: {
            order: 2,
            filter: true
        }
    })
 body: string;
 */
@Component({
  selector: 'smart-crud-filters',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="smart:flex smart:h-full smart:flex-col">
      @if (!hideMenu()) {
        <header
          class="smart:flex smart:items-center smart:justify-between smart:border-b smart:border-gray-200 smart:px-4 smart:py-3"
        >
          <h2 class="smart:text-lg smart:font-semibold smart:text-gray-900">
            {{ 'filters' | translate }}
          </h2>
          <button
            type="button"
            (click)="onClose()"
            aria-label="close"
            class="smart:rounded smart:p-1 smart:text-gray-500 hover:smart:bg-gray-100"
          >
            ✕
          </button>
        </header>
      }
      <div
        class="smart:flex-1 smart:space-y-4 smart:overflow-y-auto smart:px-4 smart:py-3"
      >
        @for (item of list(); track item.key) {
          <smart-crud-filter
            [item]="item"
            [filter]="filter()"
          ></smart-crud-filter>
        }
      </div>
    </div>
  `,
  imports: [FilterComponent, TranslatePipe],
})
export class FiltersComponent<
  T extends IEntity<string>,
> extends FiltersBaseComponent<T> {}

<ion-header [hidden]="hideMenu">
    <ion-toolbar>
        <ion-buttons slot="end">
            <ion-button (click)="onClose()">
                <ion-icon slot="icon-only" name="close"> </ion-icon>
            </ion-button>
        </ion-buttons>
        <ion-title>{{ 'filters' | translate }}</ion-title>
    </ion-toolbar>
</ion-header>
<ion-content style="height: 100vh;">
    <ion-list>
        <ng-container *ngFor="let item of list">
            <smart-crud-filter [item]="item" [filter]="filter$ | async"></smart-crud-filter>
        </ng-container>
    </ion-list>
    <div class="menu-bottom-space">
        &nbsp;
    </div>
</ion-content>
