// packages/shared/angular/src/lib/components/export/export.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ViewEncapsulation,
} from '@angular/core';

import { ButtonComponent } from '../button';
import { ExportBaseComponent } from './base/base.component';

@Component({
  selector: 'smart-export',
  template: `
    <smart-button [options]="buttonOptions" [disabled]="!value()">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 20 20"
        fill="currentColor"
        class="smart:size-5"
      >
        <path
          d="M10.75 2.75a.75.75 0 0 0-1.5 0v8.614L6.295 8.235a.75.75 0 1 0-1.09 1.03l4.25 4.5a.75.75 0 0 0 1.09 0l4.25-4.5a.75.75 0 0 0-1.09-1.03l-2.955 3.129V2.75Z"
        />
        <path
          d="M3.5 12.75a.75.75 0 0 0-1.5 0v2.5A2.75 2.75 0 0 0 4.75 18h10.5A2.75 2.75 0 0 0 18 15.25v-2.5a.75.75 0 0 0-1.5 0v2.5c0 .69-.56 1.25-1.25 1.25H4.75c-.69 0-1.25-.56-1.25-1.25v-2.5Z"
        />
      </svg>
    </smart-button>
  `,
  imports: [ButtonComponent],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ExportComponent extends ExportBaseComponent {
  buttonOptions = {
    click: () => this.onClick(),
  };
}

<!--<ion-button title="export" (click)="onClick()" slot="icon-only">-->
<!--  <ion-icon name="download"></ion-icon>-->
<!--</ion-button>-->

// packages/shared/react/src/lib/components/export/export.tsx
import { useMemo } from 'react';

import { SmartExportProps } from './export.types';
import { useExport } from './use-export';
import { IButtonOptions } from '../../models';
import { SmartButton } from '../button/button';

/**
 * `<smart-export>`: a download-icon `SmartButton` that calls
 * `handler(value, fileName)`. Disabled while `value` is empty; `className`
 * goes on the button.
 */
export function SmartExport(props: SmartExportProps) {
  const { value, className } = props;
  const { onClick } = useExport(props);

  const buttonOptions = useMemo<IButtonOptions>(
    () => ({ click: () => void onClick() }),
    [onClick],
  );

  return (
    <SmartButton
      options={buttonOptions}
      disabled={!value}
      className={className}
    >
      <svg
        aria-hidden="true"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 20 20"
        fill="currentColor"
        className="smart:size-5"
      >
        <path d="M10.75 2.75a.75.75 0 0 0-1.5 0v8.614L6.295 8.235a.75.75 0 1 0-1.09 1.03l4.25 4.5a.75.75 0 0 0 1.09 0l4.25-4.5a.75.75 0 0 0-1.09-1.03l-2.955 3.129V2.75Z" />
        <path d="M3.5 12.75a.75.75 0 0 0-1.5 0v2.5A2.75 2.75 0 0 0 4.75 18h10.5A2.75 2.75 0 0 0 18 15.25v-2.5a.75.75 0 0 0-1.5 0v2.5c0 .69-.56 1.25-1.25 1.25H4.75c-.69 0-1.25-.56-1.25-1.25v-2.5Z" />
      </svg>
      <span className="smart:sr-only">Export</span>
    </SmartButton>
  );
}
